//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechBuzzApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Techbuzz_testEntities : DbContext
    {
        public Techbuzz_testEntities()
            : base("name=Techbuzz_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EXPERIENCE> EXPERIENCEs { get; set; }
        public virtual DbSet<JOB_APPIED> JOB_APPIED { get; set; }
        public virtual DbSet<JOB_POSTINGS> JOB_POSTINGS { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<TEST_SCORES> TEST_SCORES { get; set; }
        public virtual DbSet<USER_QUERY> USER_QUERY { get; set; }
        public virtual DbSet<USER_RESPONSE> USER_RESPONSE { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    
        public virtual int spInsertUserData(string fIRST_NAME, string mIDDLE_NAME, string lAST_NAME, string pHONE_NUMBER, string eMAIL_ADDRESS, string lOGINID, string pWD, string uSER_GROUP, string eXPERIENCE_ID)
        {
            var fIRST_NAMEParameter = fIRST_NAME != null ?
                new ObjectParameter("FIRST_NAME", fIRST_NAME) :
                new ObjectParameter("FIRST_NAME", typeof(string));
    
            var mIDDLE_NAMEParameter = mIDDLE_NAME != null ?
                new ObjectParameter("MIDDLE_NAME", mIDDLE_NAME) :
                new ObjectParameter("MIDDLE_NAME", typeof(string));
    
            var lAST_NAMEParameter = lAST_NAME != null ?
                new ObjectParameter("LAST_NAME", lAST_NAME) :
                new ObjectParameter("LAST_NAME", typeof(string));
    
            var pHONE_NUMBERParameter = pHONE_NUMBER != null ?
                new ObjectParameter("PHONE_NUMBER", pHONE_NUMBER) :
                new ObjectParameter("PHONE_NUMBER", typeof(string));
    
            var eMAIL_ADDRESSParameter = eMAIL_ADDRESS != null ?
                new ObjectParameter("EMAIL_ADDRESS", eMAIL_ADDRESS) :
                new ObjectParameter("EMAIL_ADDRESS", typeof(string));
    
            var lOGINIDParameter = lOGINID != null ?
                new ObjectParameter("LOGINID", lOGINID) :
                new ObjectParameter("LOGINID", typeof(string));
    
            var pWDParameter = pWD != null ?
                new ObjectParameter("PWD", pWD) :
                new ObjectParameter("PWD", typeof(string));
    
            var uSER_GROUPParameter = uSER_GROUP != null ?
                new ObjectParameter("USER_GROUP", uSER_GROUP) :
                new ObjectParameter("USER_GROUP", typeof(string));
    
            var eXPERIENCE_IDParameter = eXPERIENCE_ID != null ?
                new ObjectParameter("EXPERIENCE_ID", eXPERIENCE_ID) :
                new ObjectParameter("EXPERIENCE_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertUserData", fIRST_NAMEParameter, mIDDLE_NAMEParameter, lAST_NAMEParameter, pHONE_NUMBERParameter, eMAIL_ADDRESSParameter, lOGINIDParameter, pWDParameter, uSER_GROUPParameter, eXPERIENCE_IDParameter);
        }
    
        public virtual int spInsertUserQueryData(string fULL_NAME, string eMAIL_ADDRESS, string uSER_DESC)
        {
            var fULL_NAMEParameter = fULL_NAME != null ?
                new ObjectParameter("FULL_NAME", fULL_NAME) :
                new ObjectParameter("FULL_NAME", typeof(string));
    
            var eMAIL_ADDRESSParameter = eMAIL_ADDRESS != null ?
                new ObjectParameter("EMAIL_ADDRESS", eMAIL_ADDRESS) :
                new ObjectParameter("EMAIL_ADDRESS", typeof(string));
    
            var uSER_DESCParameter = uSER_DESC != null ?
                new ObjectParameter("USER_DESC", uSER_DESC) :
                new ObjectParameter("USER_DESC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertUserQueryData", fULL_NAMEParameter, eMAIL_ADDRESSParameter, uSER_DESCParameter);
        }
    
        public virtual ObjectResult<spUserLogin_Result> spUserLogin(string loginId, string password)
        {
            var loginIdParameter = loginId != null ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUserLogin_Result>("spUserLogin", loginIdParameter, passwordParameter);
        }
    }
}
