//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechBuzzApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_POSTINGS
    {
        public int JOB_ID { get; set; }
        public string JOB_TITLE { get; set; }
        public string JOB_DESCRIPTION { get; set; }
        public string COMPANY { get; set; }
        public string experience { get; set; }
        public string posted_by { get; set; }
        public string category { get; set; }
        public string Location { get; set; }
    }
}
