//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechBuzzApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEST_SCORES
    {
        public int TEST_SCORE_ID { get; set; }
        public string LOGINID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string EXPERIENCE_ID { get; set; }
        public string FRONT_END_SCORE { get; set; }
        public string BACK_END_SCORE { get; set; }
        public string DATABASE_SCORE { get; set; }
        public Nullable<System.DateTime> TEST_TAKEN_DATE { get; set; }
    }
}
