//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechBuzzApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_RESPONSE
    {
        public int USER_RESPONSE_ID { get; set; }
        public Nullable<int> QUES_ID { get; set; }
        public string USER_RESP_ANS { get; set; }
        public string LOGINID { get; set; }
        public Nullable<int> USERID { get; set; }
    }
}
