//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechBuzzApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int USERID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string LOGINID { get; set; }
        public string PWD { get; set; }
        public string USER_GROUP { get; set; }
        public string EXPERIENCE_ID { get; set; }
    }
}
