//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechBuzzApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_QUERY
    {
        public int QUERY_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string USER_DESC { get; set; }
    }
}
